# Generated by Django 3.2.16 on 2024-12-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('rua', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('CEP', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
            ],
        ),
    ]
