# Generated by Django 3.2.16 on 2024-12-24 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20241224_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='CEP',
            new_name='cep',
        ),
    ]
